name: Dustin
favicon: null
layout_spectrum: 0.39733
typography_spectrum: 0.73847
title: Dustin W. Stout
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3e424d'
    - '#f2353b'
    - '#ffffff'
    - '#b17165'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
