name: Dustin
favicon: null
layout_spectrum: 0.62437
typography_spectrum: 0.72678
title: Dustin W. Stout
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#ca3538'
    - '#6aca3f'
    - '#727272'
  brandStrength: 0.8728901518043131
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
